# ---
version: 0.1

# env:
#   variables:
#     key: "value"

# phases:
#   install:
#     commands:
#       - make install
#   pre_build:
#     commands:
#       - make test
#   build:
#     commands:
#       - make build
#   post_build:
#     commands:
#       - echo Uploading artifact to S3.
#       - aws s3 cp $ARTIFACT_FILENAME s3://$RELEASE_BUCKET_NAME/$ARTIFACT_NAME
#       - echo Updating release key.
#       - aws --region=eu-west-2 ssm put-parameter --name /$APP_NAME/releases/$CODEBUILD_RESOLVED_SOURCE_VERSION --value $ARTIFACT_FILENAME --type String --overwrite
#       - aws --region=eu-west-2 ssm put-parameter --name /$APP_NAME/releases/latest --value $ARTIFACT_FILENAME --type String --overwrite

# artifacts:
#   files:
#     - $ARTIFACT_FILENAME



phases:
  install:
    commands:
      # Node, NPM, AWS-CLI are preinstalled on this CodeBuild image.
      - sudo apt-get update -y && sudo apt-get install -y make apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update -y && sudo apt-get install -y yarn
  build:
    commands:
      - make test ENV_FILE_PATH=env/example.env


